qatracker:
    dataSeries:
        lines-of-code:
            class: Alxvng\QATracker\DataProvider\XpathProvider
            arguments:
                - 'docs/qa/phploc/log.xml'
                - '/phploc/loc'
        non-comment-lines-of-code:
            class: Alxvng\QATracker\DataProvider\XpathProvider
            arguments:
                - 'docs/qa/phploc/log.xml'
                - '/phploc/ncloc'
        average-complexity-per-class:
            class: Alxvng\QATracker\DataProvider\XpathProvider
            arguments:
                - 'docs/qa/phploc/log.xml'
                - '/phploc/classCcnAvg'
        total-duplicated-lines:
            class: Alxvng\QATracker\DataProvider\XpathSumProvider
            arguments:
                - 'docs/qa/phpcpd/log.xml'
                - '/pmd-cpd/duplication/@lines'
        total-duplicated-lines-percent:
            provider: 'total-duplicated-lines'
            totalPercentProvider: 'lines-of-code'
        total-duplications:
            class: Alxvng\QATracker\DataProvider\XpathCountProvider
            arguments:
                - 'docs/qa/phpcpd/log.xml'
                - '/pmd-cpd/duplication'
        average-maintenance-index:
            class: Alxvng\QATracker\DataProvider\JsonPathAverageProvider
            arguments:
                - 'docs/qa/phpmetrics/report.json'
                - '$.*.mi'
        total-code-coverage-(lines):
            class: Alxvng\QATracker\DataProvider\XpathProvider
            arguments:
                - 'docs/qa/phpunit/coverage.xml/index.xml'
                - '/ns:phpunit/ns:project/ns:directory/ns:totals/ns:lines/@percent'
                - {prefix: 'ns', namespace: 'https://schema.phpunit.de/coverage/1.0'}
        total-crap:
            class: Alxvng\QATracker\DataProvider\XpathProvider
            arguments:
                - 'docs/qa/phpunit/coverage.crap4j'
                - '/crap_result/stats/totalCrap'
        total-phpstan-errors:
            class: Alxvng\QATracker\DataProvider\JsonPathProvider
            arguments:
                - 'docs/qa/phpstan/log.json'
                - '$.totals.file_errors'

    # documentation :
    # graphSettings : documentation is available at https://goat1000.com/svggraph-options.php

    # note :
    # at the moment only the first serie is used to generate chart
    # multiple data series chart is not available, maybe soon ... PR accepted ;-)
    charts:
        line-of-code-line:
            type: Goat1000\SVGGraph\LineGraph
            dataSeries:
                - 'lines-of-code'
            withHistory: true
            graphSettings:
                graph_title: 'Lines of code'
        line-of-code-bar:
            type: Goat1000\SVGGraph\BarGraph
            dataSeries:
                - 'lines-of-code'
            withHistory: true
            graphSettings:
                graph_title: 'Lines of code'
        total-duplicated-lines-percent:
            type: Goat1000\SVGGraph\LineGraph
            dataSeries:
                - 'total-duplicated-lines-percent'
            withHistory: true
            graphSettings:
                graph_title: 'Duplication pourcentage'
                units_y: '%'
#        -   name: 'Maintainability'
#            dataSeries: {'total-crap', 'average-maintenance-index', 'total-phpstan-errors'}
#            withHistory: false
