qatracker:
    dataSeries:
        -   id: 'lines-of-code'
            class: Alxvng\QATrackerDataProvider\XpathProvider
            arguments:
                - 'docs/qa-tools/phploc/log.xml'
                - '/phploc/loc'
        -   id: 'non-comment-lines-of-code'
            class: Alxvng\QATrackerDataProvider\XpathProvider
            arguments:
                - 'docs/qa-tools/phploc/log.xml'
                - '/phploc/ncloc'
        -   id: 'average-complexity-per-class'
            class: Alxvng\QATrackerDataProvider\XpathProvider
            arguments:
                - 'docs/qa-tools/phploc/log.xml'
                - '/phploc/classCcnAvg'
        -   id: 'total-duplicated-lines'
            class: Alxvng\QATrackerDataProvider\XpathSumProvider
            arguments:
                - 'docs/qa-tools/phpcpd/log.xml'
                - '/pmd-cpd/duplication/@lines'
        -   id: 'total-duplicated-lines-percent'
            provider: 'total-duplicated-lines'
            totalPercentProvider: 'lines-of-code'
        -   id: 'total-duplications'
            class: Alxvng\QATrackerDataProvider\XpathCountProvider
            arguments:
                - 'docs/qa-tools/phpcpd/log.xml'
                - '/pmd-cpd/duplication'
        -   id: 'average-maintenance-index'
            class: Alxvng\QATrackerDataProvider\JsonPathAverageProvider
            arguments:
                - 'docs/qa-tools/phpmetrics/report.json'
                - '$.*.mi'
        -   id: 'total-code-coverage-(lines)'
            class: Alxvng\QATrackerDataProvider\XpathProvider
            arguments:
                - 'docs/qa-tools/phpunit/coverage.xml/index.xml'
                - '/ns:phpunit/ns:project/ns:directory/ns:totals/ns:lines/@percent'
                - {prefix: 'ns', namespace: 'https://schema.phpunit.de/coverage/1.0'}
        -   id: 'total-crap'
            class: Alxvng\QATrackerDataProvider\XpathProvider
            arguments:
                - 'docs/qa-tools/phpunit/coverage.crap4j'
                - '/crap_result/stats/totalCrap'
        -   id: 'total-phpstan-errors'
            class: Alxvng\QATrackerDataProvider\JsonPathProvider
            arguments:
                - 'docs/qa-tools/phpstan/log.json'
                - '$.totals.file_errors'

    # documentation :
    # graphSettings : documentation is available at https://goat1000.com/svggraph-options.php

    # note :
    # at the moment only the first serie is used to generate chart
    # multiple data series chart is not available, maybe soon ... PR accepted ;-)
    charts:
        -   type: Goat1000\SVGGraph\LineGraph
            dataSeries:
                - 'lines-of-code'
            withHistory: true
            graphSettings:
                graph_title: 'Lines of code'
        -   type: Goat1000\SVGGraph\BarGraph
            dataSeries:
                - 'lines-of-code'
            withHistory: true
            graphSettings:
                graph_title: 'Lines of code'
        -   type: Goat1000\SVGGraph\LineGraph
            dataSeries:
                - 'total-duplicated-lines-percent'
            withHistory: true
            graphSettings:
                graph_title: 'Duplication pourcentage'
                units_y: '%'
#        -   name: 'Maintainability'
#            dataSeries: {'total-crap', 'average-maintenance-index', 'total-phpstan-errors'}
#            withHistory: false
