qatracker:
    series:
        -
            name : 'loc'
            provider: App\DataProvider\XpathProvider
            arguments:
                - 'qa/phploc/log.xml'
                - '/phploc/loc'