# This is a basic workflow to help you get started with Actions

name: Quality

on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Start project
                run: |
                    cd docker
                    make restart
            -   name: Unit tests
                run: |
                    make test
    code-style:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Start project
                run: |
                    cd docker
                    make restart
            -   name: Check code style
                run: |
                    make cs