# This is a basic workflow to help you get started with Actions

name: Docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - 'master'
            - '0*'
            - '*-ci'
    pull_request:
        branches:
            - 'master'
            - '0*'
            - '*-ci'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    publish-image:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v2
            -   name: Publish to Registry
                uses: elgohr/Publish-Docker-Github-Action@master
                with:
                    name: alxvgt/qatracker/base
                    username: ${{ github.actor }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
                    registry: docker.pkg.github.com
                    workdir: docker
